//  Created by Moazam Mir on 4/9/20.
//  Copyright © 2020 Moazam. All rights reserved.
//

import UIKit

struct WritingBrain 
{
    var questionArray = [String]()
    var questionNumber = 0
    var timeLimitReached = false
    var maxQuestions = 1000
    let defaults = UserDefaults.standard
    
    
    //CHECK THE LENGTH OF ANSWER ENTERED
    func checkAnswerLength(text : String) -> Bool
    {
        if text.count >= 10
        {
            return true
        }
        else
        {
            return false
        }
    }
 
    // Update Question Number
   mutating func nextQuestion()
    {
            if let num = defaults.string(forKey: "questionNumber")
            { self.questionNumber = Int(num)!  }
        print("Question Number is \(questionNumber)")
            
        if questionNumber + 1 < questionArray.count
            {
                questionNumber += 1
                defaults.set(questionNumber, forKey: "questionNumber")
            }
            else{
                questionNumber = 0
                defaults.set(questionNumber, forKey: "questionNumber")

            }
    }
       
        func getNextQuestion() -> String {
            print(questionNumber)
            return questionArray[questionNumber]
        }
        
    
    init()
    {
     

        if let num = defaults.string(forKey: "questionNumber")
                  { self.questionNumber = Int(num)!  }
        
        //Question Set 1
        questionArray.append(" Describe your favorite sandwich." )
        questionArray.append(" What are the 3 places you’d like to visit for the first time and 3 places to revisit. " )
        questionArray.append(" What’s your favorite thing about spring, summer, fall and winter?" )
        questionArray.append(" What’s your favorite holiday and why?" )
        questionArray.append(" If you could be an animal, what would it be and why? " )
        questionArray.append(" List 5 of your favorite musical bands/composer/artists. " )
        questionArray.append(" Describe how you travel to NYIT." )
        questionArray.append(" List 4 things that remind you of Fall.")
        questionArray.append(" List 4 things that start with the letter “P”" )
        questionArray.append(" List 4 states." )
        
        
        questionArray.append(" List 4 countries.")
        questionArray.append(" List 4 US cities. ")
        questionArray.append(" What do you pack in your suitcase for a weeklong trip to see a friend? ")
        questionArray.append(" Describe a beautiful scene in nature.")
        questionArray.append(" If you have to choose a different career, what would it be and why?")
        questionArray.append(" List 4 of your favorite movies.")
        questionArray.append(" List 4 of your favorite TV shows.")
        questionArray.append(" List 3 of your favorite actresses.")
        questionArray.append(" What’s your favorite story and why. ")
        questionArray.append(" List  4 of your favorite foods. ")
        
        questionArray.append(" Describe how do you make a peanut butter sandwich?  ")
        questionArray.append(" Name 10 different animals. ")
        questionArray.append(" Describe your favorite pair of shoes.")
        questionArray.append(" List 3 NYC is famous for. ")
        questionArray.append(" What’s your favorite sport and why.  ")
        questionArray.append(" Name 2 of your favorite athletes.  ")
        questionArray.append(" Do you think it’s better to be a child, teenager, or adult  and why. ")
        questionArray.append(" Name 2 things to get a good night sleep. ")
        questionArray.append(" Name 4 types of drinks.")
        questionArray.append(" List 4 different languages. ")
        questionArray.append(" Tell a good memory from your childhood.")
        questionArray.append(" Name 3 universities.")
        questionArray.append(" Write down 1 to 10 in any order that you like")
        questionArray.append(" Name 3 musical instruments. ")
        questionArray.append(" Name 2 brands of cars.")
        questionArray.append(" Describe your ideal car.")
        questionArray.append(" Describe the contents of your wallet (or purse).")
        questionArray.append(" Describe the outfit that you wore today.")
        questionArray.append(" Name 2 types of hats.")
        questionArray.append(" Name 2 things to do to relax.")
        questionArray.append( " Describe the contents of a favorite book.")
        questionArray.append(" Name 3 scary animals and where would you find them. ")
        questionArray.append(" Name 4 pieces of technology that you “must” have.")
        questionArray.append(" If you could be a superhero, what would it be and why?")
        questionArray.append( " List 4 things that annoy you. ")
        questionArray.append(" List 3 fast food restaurants.")
        questionArray.append(" Describe a funny event in your life.")
        questionArray.append( " Name 2 spices/herbs.")
        questionArray.append(" Name 2 politicians.")
        questionArray.append(" What would you do with 5 million dollars? ")
        questionArray.append(" Describe your favorite outfit. ")
        questionArray.append( " Describe your favorite dessert.")
        questionArray.append(" You’re making dinner for 5, who would you invite from the past and why.")
        questionArray.append( " Describe your ideal house.")
        questionArray.append( " Describe your favorite Halloween costume. ")
        questionArray.append(" List 2 things that you really like about NY.")
        questionArray.append(" Give 2 pieces of advice.")
        questionArray.append( " Describe your favorite or ideal pet.")
        questionArray.append(" Rank your favorite way to travel and why: car, train, and bike.")
        questionArray.append(" Describe the shoes you are wearing.")
        questionArray.append(" What is favorite smell and why.")
        questionArray.append(" What would be the best job, and why.")
        questionArray.append(" What would the worst job, and why.")
        questionArray.append(" If you were granted three wishes, what would they be?")
        questionArray.append( " Describe the house/neighborhood you grew up in.")
        questionArray.append(" Describe you ideal home.")
        questionArray.append(" Describe your favorite hobby.")
        questionArray.append(" What’s your favority outdoor activity and why.")
        
        //New Questions, 23Jan 2020
        questionArray.append( "How would you describe a dog to someone.")
        questionArray.append("How would you describe a bird to someone")
        questionArray.append( "How would you describe a fish to someone ")
        questionArray.append("How would you describe a train to someone.")
        questionArray.append("How would you describe a book to someone.")
        questionArray.append("How would you describe a truck to someone.")
        questionArray.append("How would you describe rock music and rock musicians.")
        questionArray.append("How would you describe a newspaper to someone.")
        questionArray.append("How would you describe a democracy to someone.")
        questionArray.append( "How would you describe a kitchen to someone.")
        questionArray.append("How would you describe a park to someone.")
        questionArray.append("How would you describe a cell phone to someone.")
        questionArray.append( "How would you describe a belt to someone.")
        questionArray.append("How would you describe a headache to someone.")
        questionArray.append("How would you describe a traffic jam to someone.")
        questionArray.append("How would you describe an apartment building to someone.")
        questionArray.append("How would you describe a hardware store to someone.")
        questionArray.append("How would you describe Texas to someone.")
        questionArray.append("How would you describe Hollywood to someone.")
        questionArray.append("How would you describe China to someone.")
        questionArray.append("How would you describe a sport you know to someone.")
        questionArray.append("How would you describe a fireman to someone.")
        questionArray.append("How would you describe a teacher to someone.")
        questionArray.append("How would you describe a farm to someone.")
        questionArray.append("How would you describe high school to someone.")
        questionArray.append("List 5-15 magazines or newspapers")
        questionArray.append("How would you describe yourself to a reporter.")
        questionArray.append("Name 5-10 colors")
        
        //New questions 4/6/2020 - Virraimy
//                     listOne.append(Question(text: "Name things that money can not buy."))
//                     listOne.append(Question(text: "What are your favorite Pokemons?"))
//                     listOne.append(Question(text: "Why do we age?"))
//                     listOne.append(Question(text: "What's your favorite way to spend a lazy day?"))
//                     listOne.append(Question(text: "Write a small diary entry."))
//                     listOne.append(Question(text: "Write the first things that comes to mind when you hear the word: summer."))
//                     listOne.append(Question(text: "List what do you look forward to every week"))
//                     listOne.append(Question(text: "What are things you bought, but never used it?"))
//                     listOne.append(Question(text: "What do you think will be the next innovations?"))
//                     listOne.append(Question(text: "Name medicines you can buy without a doctor's prescription"))
//                     listOne.append(Question(text: "List dog names."))
//                     listOne.append(Question(text: "What makes a good photo?"))
//                     listOne.append(Question(text: "Why is sleep important?"))
//                     listOne.append(Question(text: "What's the color that describes your mood most of the time? and why?"))
//                     listOne.append(Question(text: "Name social media platforms."))
//                     listOne.append(Question(text: "What are some  of your new year's resolutions?"))
//                     listOne.append(Question(text: "What makes a good commercial?"))
//                     listOne.append(Question(text: "What are the best books you’ve read?"))
//                     listOne.append(Question(text: "What foods you dislike?"))
//                     listOne.append(Question(text: "What skills would you teach in two minutes?"))
//                     listOne.append(Question(text: "What are your most prized possessions?"))
//                     listOne.append(Question(text: "Name the best 3 countries to travel."))
//                     listOne.append(Question(text: "What do you want to be doing when you’re 80?"))
//                     listOne.append(Question(text: "Name ways in which life makes us humble everyday."))
//                     listOne.append(Question(text: "Can you live without internet? Explain your answer."))
//                     listOne.append(Question(text: "What's on your bucket list?"))
//                     listOne.append(Question(text: "Name countries that speak English."))
//                     listOne.append(Question(text: "Name your favorite hobbies."))
//                     listOne.append(Question(text: "Which one is better: coffee or tea? and  why?"))
//                     listOne.append(Question(text: "Is luck real? Explain your answer."))
//                     listOne.append(Question(text: "What's are most useful things you own?"))
//                     listOne.append(Question(text: "What's your favorite season? and why?"))
//                     listOne.append(Question(text: "Name characteristics of a healthy friendship."))
//                     listOne.append(Question(text: "If you had to describe your life in one line, what would it be?"))
//                     listOne.append(Question(text: "Name the best places to do homework?"))
//                     listOne.append(Question(text: "How important is the census?"))
//                     listOne.append(Question(text: "What's the  difference between orange, lemons and grapefruits?"))
//                     listOne.append(Question(text: "Do you consider coffee and addiction? Explain your answer."))
//                     listOne.append(Question(text: "List movies from 2019."))
//                     listOne.append(Question(text: "What foods brings you back go your childhood?"))
//                     listOne.append(Question(text: "Do you believe in coincidence or predetermination? And why?"))
//                     listOne.append(Question(text: "You're left stranded on an island, what's your first survival move? "))
//                     listOne.append(Question(text: "You are now the president. What changes would you make?"))
//                     listOne.append(Question(text: "Name forms of transportation through land."))
//                     listOne.append(Question(text: "Name things you will find in a circus ?"))
//                     listOne.append(Question(text: "Does magic exist? Explain your answer."))
//                     listOne.append(Question(text: "Name things you will find on an airplane."))
//                     listOne.append(Question(text: "Imagine you have wings to fly. What would you do?"))
//                     listOne.append(Question(text: "Should video games be considered a sport? Explain your answer."))
//                     listOne.append(Question(text: "Name things you will find at a doctor’s office."))
//
//                     listOne.append(Question(text: "Should rich people have to pay more taxes? And why?"))
//                     listOne.append(Question(text: "Do you find it easier to make new friends online or in person? And why"))
//                     listOne.append(Question(text: "How should you handle the end of a friendship?"))
//                     listOne.append(Question(text: "Is breakfast really the most important meal of the day? And why?"))
//                     listOne.append(Question(text: "Is It ethical to eat meat? Explain your answer."))
//                     listOne.append(Question(text: "Name things you will find at a Zoo?"))
//                     listOne.append(Question(text: "If you Could time-travel, what places would you go?"))
//                     listOne.append(Question(text: "How do You celebrate your Birthday?"))
//                     listOne.append(Question(text: "Do you believe in ghosts? Explain your answer."))
//                     listOne.append(Question(text: "What do you od on a snowy day?"))
//                     listOne.append(Question(text: "What would your ideal summer camp be like?"))
//                     listOne.append(Question(text: "Would life be better without time zones?"))
//                     listOne.append(Question(text: "Is privacy more important than national security? Explain. "))
//                     listOne.append(Question(text: "Should teachers be allowed to have guns?"))
//                     listOne.append(Question(text: "What would you ask Steve Jobs?"))
//                     listOne.append(Question(text: "What's your first response to a fire drill?"))
//                     listOne.append(Question(text: "What's the first thing you notice about a person?"))
//                     listOne.append(Question(text: "Do you believe in aliens? Explain your answer."))
//                     listOne.append(Question(text: "Your life is a movie, describe it in a sentence?"))
//                     listOne.append(Question(text: "Describe a bad experience using 3 song titles."))
//                     listOne.append(Question(text: "What are the cons of sleeping with the AC on?"))
//                     listOne.append(Question(text: "Name things you will find at a train station."))
//                     listOne.append(Question(text: "Name things you will find at an aquarium."))
//                     listOne.append(Question(text: "Did you think coronavirus was a biological weapon?"))
//                     listOne.append(Question(text: "Name 4  professions."))
//                     listOne.append(Question(text: "What are your thoughts on death penalty?"))
//                     listOne.append(Question(text: "What are your thoughts on abortion?"))
//                     listOne.append(Question(text: "What are your thoughts on mass shootings?"))
//                     listOne.append(Question(text: "What are your thoughts on police brutality?"))
//                     listOne.append(Question(text: "What are your thoughts on gentrification?"))
//                     listOne.append(Question(text: "What are your thoughts on white privilege?"))
//                      listOne.append(Question(text: "What are your thoughts on gay marriage?"))
//                      listOne.append(Question(text: "What are your thoughts on gun rights?"))
//                      listOne.append(Question(text: "What are your thoughts on transgender athletes?"))
//                      listOne.append(Question(text: "What are your thoughts on hijab"))
//                      listOne.append(Question(text: "What are your thoughts on racism?"))
//                      listOne.append(Question(text: "What are your thoughts on student loans?"))
//                      listOne.append(Question(text: "What are the best states to live in?"))
//                      listOne.append(Question(text: "Name places you do not mind waiting at."))
//                      listOne.append(Question(text: "If you could disinvent 3 thing, what would they be?"))
//                      listOne.append(Question(text: "Name cereal brands"))
//                      listOne.append(Question(text: "Name ingredients to cook chicken."))
//                      listOne.append(Question(text: "Why is important to recycle?"))
//                      listOne.append(Question(text: "What are you most looking forward to in the next 10 years?"))
//                      listOne.append(Question(text: "Name 4 famous singers ?"))
//                      listOne.append(Question(text: "List things you will find at a conference room."))
//                      listOne.append(Question(text: "Name things you will find at a classroom."))
//                      listOne.append(Question(text: " Why is important to save money?"))
//                      listOne.append(Question(text: "Do you believe in the after life? Explain your answer."))
//                      listOne.append(Question(text: "Name 3 animals from the sea."))
//                      listOne.append(Question(text: "Name things you will find at a wedding."))
//                      listOne.append(Question(text: " Name 3 United States holidays."))
//                      listOne.append(Question(text: "List 3 names with the letter M "))
//                      listOne.append(Question(text: "What don't you like about your surroundings?"))
//                      listOne.append(Question(text: "What would you change about your surroundings?"))
//                      listOne.append(Question(text: "List 3 animals you will find in Central Park. "))
//                      listOne.append(Question(text: "If you had the world's attention for 30 seconds, what would you say?"))
//                      listOne.append(Question(text: "Name 3 things you will find at a graduation."))
//                      listOne.append(Question(text: "List 2 types of  cakes.?"))
//                      listOne.append(Question(text: "Name 3 religions."))
//                      listOne.append(Question(text: "What makes someone a hero?"))
//                      listOne.append(Question(text: "If there was an extra hour every day, what would you do with it?"))
//                      listOne.append(Question(text: "Describe your favorite type of pizza?"))
//                      listOne.append(Question(text: "Name things you will find at a dinner table."))
//                      listOne.append(Question(text: "If you found $100 on the ground, what would you do with it?"))
//                      listOne.append(Question(text: "What are some things you shouldn't say at work?"))
//                      listOne.append(Question(text: "What do you think your life will look like in 10 years?"))
//                      listOne.append(Question(text: "If you were a waiter and had a rude customer, what would you do?"))
//                      listOne.append(Question(text: "Name 3 different majors."))
//                      listOne.append(Question(text: "List bad habits?"))
//                      listOne.append(Question(text: "List good habits."))
//                      listOne.append(Question(text: "While driving what’s one thing you should always remember?"))
//                      listOne.append(Question(text: "What would you do if you were the lone survivor of a plane crash?"))
//                      listOne.append(Question(text: "Describe what it will be like to live on the moon."))
//                      listOne.append(Question(text: "Name things you do during easter."))
//                      listOne.append(Question(text: "Name 3 cleaning products."))
//                      listOne.append(Question(text: "Have you ever done something heroic?"))
//                      listOne.append(Question(text: "Biggest prank you’ve played on someone?"))
//                      listOne.append(Question(text: "Biggest prank someone played on you?"))
//                      listOne.append(Question(text: "If you were to get a daughter, what would you name her?"))
//                      listOne.append(Question(text: "If you were to get a son, what would you name her?"))
//                      listOne.append(Question(text: "List US states with warm weather."))
//                      listOne.append(Question(text: "Name countries that speak spanish."))
//                      listOne.append(Question(text: "Name objects/things that start with the letter A"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter B"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter C"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter D"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter F"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter G"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter R"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter P"))
//                      listOne.append(Question(text: "Name objects/things that start with the letter M"))
//                      listOne.append(Question(text: "Would you donate a kidney? And why?"))
//                      listOne.append(Question(text: "What new smartphone features would you invent?"))
//                      listOne.append(Question(text: "What animal do you think should be renamed?"))
//                      listOne.append(Question(text: "List things that you will find in the kitchen."))
//                      listOne.append(Question(text: "List things you will find at a concert."))
//                      listOne.append(Question(text: "Name 2 cartoons."))
//                      listOne.append(Question(text: "Name 3 sports."))
//                      listOne.append(Question(text: "What should be the goal of humanity?"))
//                      listOne.append(Question(text: "List the positives of social media."))
//                      listOne.append(Question(text: "Has social media been a net positive or a net negative for our society? Why?"))
//                      listOne.append(Question(text: " Is some degree of censorship necessary? Explain your answer."))
//                      listOne.append(Question(text: "Football or Basketball? Explain your answer."))
//                      listOne.append(Question(text: "Pancake or Waffle? Explain your answer"))
//                      listOne.append(Question(text: "Name 3 types of music genres."))
//                      listOne.append(Question(text: " What’s worse: runny nose or dry eyes? Explain your answer."))
//                      listOne.append(Question(text: "Spotify or Apple music? Explain your answer"))
//                      listOne.append(Question(text: "Name 5 things you will find at a Wholes Food store"))
//                      listOne.append(Question(text: "Corn chips or Doritos? Explain your answer"))
//                      listOne.append(Question(text: "Would you rather live on the beach or in a cabin in the woods? And why"))
//                      listOne.append(Question(text: "Would you rather be an amazing painter or a brilliant mathematician? And why"))
//                      listOne.append(Question(text: "Would you rather have a completely automated home or a self-driving car?"))
//                      listOne.append(Question(text: "French fries or onion rings? Explain your answer"))
//                      listOne.append(Question(text: "Apple or cherry pie? Explain your answer"))
//                      listOne.append(Question(text: "Favorite way to spend a hot summer day?"))
//                      listOne.append(Question(text: "Would you rather live in a cave or live in a tree house?"))
//                      listOne.append(Question(text: " Would you rather be a famous director or a famous actor?"))
//                      listOne.append(Question(text: "What are the benefits of running?"))
//                      listOne.append(Question(text: "Would you rather spend the rest of your life with a sailboat as your home or an RV as your home?"))
//                      listOne.append(Question(text: "Public library or bookstore? Explain your answer"))
//                      listOne.append(Question(text: "Tent or RV? Explain your answer"))
//                      listOne.append(Question(text: "Bowling or tennis? Explain your answer"))
//                      listOne.append(Question(text: "Cold cereal or oatmeal? Explain your answer"))
//                      listOne.append(Question(text: "Family run or chain restaurant? Explain your answer"))
//                      listOne.append(Question(text: "Would you rather have amazingly fast typing/texting speed or be able to read ridiculously fast?"))
//                      listOne.append(Question(text: " Jogging or Hiking? Explain your answer"))
//                      listOne.append(Question(text: "Zip lining or  snowboarding? And why?"))
//                      listOne.append(Question(text: " City or Countryside? Explain your answer"))
//                      listOne.append(Question(text: "Book or eBook? Explain your answer"))
//                      listOne.append(Question(text: "Camping or Binge Watching Shows at Home?"))
//                      listOne.append(Question(text: "List 3 light colors"))
//                      listOne.append(Question(text: "What was cool when you were young but isn’t cool now?"))
//                      listOne.append(Question(text: "Name 3 pets."))
//                      listOne.append(Question(text: "Which are your favorite yogurt flavors?"))
//                      listOne.append(Question(text: "What lifts you up each time you feel down?"))
//                      listOne.append(Question(text: "Name 3 beverages."))
//                      listOne.append(Question(text: "Name 5 animals with 4 legs."))
//                      listOne.append(Question(text: "Which is the worst injury have you got in life?"))
//                      listOne.append(Question(text: "When were you first introduced into the social media?"))
//                      listOne.append(Question(text: "What are your thoughts on Bitcoin"))
//                      listOne.append(Question(text: "Are you planning to pursue a Phd degree? Why?"))
//                      listOne.append(Question(text: "Name three things that you cannot forget while going on a road trip?"))
//                      listOne.append(Question(text: "What would you buy if given 500$ to spend it within 15minutes?"))
//                      listOne.append(Question(text: "Where do you see yourself in 1 month?"))
//                      listOne.append(Question(text: "Where do you see yourself in 1 year ?"))
//                      listOne.append(Question(text: "Where do you see yourself in 5 years?"))
//                      listOne.append(Question(text: "Where do you see yourself in 10 years?"))
//                      listOne.append(Question(text: "Where do you see yourself in 20 years?"))
//                      listOne.append(Question(text: "Where do you see yourself in 30 years?"))
//                      listOne.append(Question(text: "Where do you see yourself in 50 years?"))
//                      listOne.append(Question(text: "McDonalds or Burger King? Explain your answer."))
//                      listOne.append(Question(text: "Pepsi or Coke? Explain your answer."))
//                      listOne.append(Question(text: "What kind of foods do you try to avoid eating?"))
//                      listOne.append(Question(text: "If you were to make your own restaurant, who would you hire as your restaurant’s chef?"))
//                      listOne.append(Question(text: "Name 3 sweet foods.?"))
//                      listOne.append(Question(text: "What’s the most saltiest things you’ve ever ate in your life?"))
//                      listOne.append(Question(text: "What’s the most cheapest things you’ve bought?"))
//                      listOne.append(Question(text: "What are things you will find at Home Depot?"))
//                      listOne.append(Question(text: "What’s the most expensive clothes you bought?"))
//                      listOne.append(Question(text: "What’s the most cheapest clothes you’ve bought?"))
//                      listOne.append(Question(text: "What makes a brand valuable?"))
//                      listOne.append(Question(text: "Can you answer a question with a question? Explain your answer."))
//                      listOne.append(Question(text: "Name 3 types of deserts."))
//                      listOne.append(Question(text: "List animals that start with the letter A."))
//                      listOne.append(Question(text: "List animals that start with the letter B."))
//                      listOne.append(Question(text: "List animals that start with the letter D."))
//                      listOne.append(Question(text: "List animals that start with the letter E."))
//                      listOne.append(Question(text: "List animals that start with the letter F."))
//                      listOne.append(Question(text: "List animals that start with the letter G."))
//                      listOne.append(Question(text: "List animals that start with the letter R."))
//                      listOne.append(Question(text: "List animals that start with the letter M."))
//                      listOne.append(Question(text: "List animals that start with the letter Z."))
//                      listOne.append(Question(text: "List animals that start with the letter L."))
//                      listOne.append(Question(text: "List animals that start with the letter R."))
//                      listOne.append(Question(text: "List animals that start with the letter S."))
//                      listOne.append(Question(text: "List animals that start with the letter W."))
//                      listOne.append(Question(text: "What cable provider do you think is the best and why ?"))
//                      listOne.append(Question(text: "Name 3 movie genres."))
//                      listOne.append(Question(text: "Name 5 fruits."))
//                      listOne.append(Question(text: "Name 3 book genres."))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter B?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter A?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter C?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter D?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter F?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter G?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter H?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter I?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter J?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter k?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter L?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter M?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter N?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter O?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter P?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter Q?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter R?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter S?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter T?"))
//                      listOne.append(Question(text: "What’s your favorite movie beginning with the letter V?"))
//                      listOne.append(Question(text: "What’s the most memorable moment at school?"))
//                      listOne.append(Question(text: "Whatsapp or Facebook Messenger? Explain your answer."))
//                      listOne.append(Question(text: "Do you prefer music in mp3 or video format? And why?"))
//                      listOne.append(Question(text: "Name 3 bugs."))
//                      listOne.append(Question(text: "Name your own smartphone with 3 words?"))
//                      listOne.append(Question(text: "If you were to invent an OS of your own, how would it be like?"))
//                      listOne.append(Question(text: "Have you bought any paid apps?"))
//                      listOne.append(Question(text: "How do you think your life without gaming be like?"))
//                      listOne.append(Question(text: "List where you can get video games from."))
//                      listOne.append(Question(text: "Name 3 United States presidents."))
//                      listOne.append(Question(text: "Name 3 places that do not exist in real life.."))
//                      listOne.append(Question(text: "Name 3 fiction characters."))
//                      listOne.append(Question(text: "If you could combine 3 video game worlds, which ones would you combine?"))
//                      listOne.append(Question(text: "If you were to remake a movie, what actors would you cast?"))
//                      listOne.append(Question(text: "Name 3 foods people have for breakfast."))
//                      listOne.append(Question(text: "Name 3 water brands."))
//                      listOne.append(Question(text: "Name 3 baseball teams."))
//                      listOne.append(Question(text: "Describe a typical NYC apartment."))
//
//                      listOne.append(Question(text: "What things can you find at a deli?"))
//                      listOne.append(Question(text: "What question do you dislike to be asked?"))
//                      listOne.append(Question(text: "Describe today's generation with one word."))
//                      listOne.append(Question(text: "Describe the sun."))
//                      listOne.append(Question(text: "Which company are you likely to invest in: IBM or HP? And why?"))
//                      listOne.append(Question(text: "What’s the time square experience like?"))
//                      listOne.append(Question(text: "Name 3 sources of energy."))
//                      listOne.append(Question(text: "What Single Message Would You Send To An Advanced Alien Species?"))
//                      listOne.append(Question(text: "How Would You Survive A Zombie Apocalypse?"))
//                      listOne.append(Question(text: "What Would Be The Worst “Buy One Get One Free” Sale Of All Time?"))
//                      listOne.append(Question(text: "What Words Of Wisdom Would You Pass On To Your Childhood Self?"))
//                      listOne.append(Question(text: "Would You Rather Have Unlimited Sushi For Life Or Unlimited Tacos For Life?"))
//                      listOne.append(Question(text: "Would You Rather Be Able To Copy And Paste In Real Life, Or Undo In Real Life?"))
//                      listOne.append(Question(text: "Name 3 class subjects."))
//                      listOne.append(Question(text: "What are two things you would do if you woke up to find yourself completely invisible?"))
//                      listOne.append(Question(text: "Give me the names of 3 objects or things you love most and why?"))
//                      listOne.append(Question(text: "If you could get away with a crime, would you? If yes, what would it be?"))
//                      listOne.append(Question(text: "What fashion trend do you wish would come back?"))
//                      listOne.append(Question(text: "Name 3 things in nature you find most beautiful?"))
//                      listOne.append(Question(text: "What fashion trend do you wish would go away?"))
//                      listOne.append(Question(text: "If someone wrote a biography about you, what do you think the title should be?"))
//                      listOne.append(Question(text: "If you could start a collection of one kind of item, what would it be?"))
//                      listOne.append(Question(text: "What color do you feel like today?"))
//                      listOne.append(Question(text: "Name 3 things you must have during a day."))
//                      listOne.append(Question(text: "Name three things you have in your bathroom right now."))
//                      listOne.append(Question(text: "What is standing in your way right now "))
//                      listOne.append(Question(text: "What makes people stand out?"))
//                      listOne.append(Question(text: "Iphone or Android? And why?"))
//                      listOne.append(Question(text: "Dogs or cats? And why?"))
//                      listOne.append(Question(text: "Car or SUV? And why?"))
//                      listOne.append(Question(text: "Python or Java? And why?"))
//                      listOne.append(Question(text: "Name board games.?"))
//                      listOne.append(Question(text: "Name 3 NYC colleges/universities."))
//                      listOne.append(Question(text: "Describe a guitar without calling it by its name."))
//                      listOne.append(Question(text: "Would you rather be blind or deaf? Explain your answer."))
//                      listOne.append(Question(text: "Name 3 bank brands."))
//                      listOne.append(Question(text: "Fried fish or steamed fish? And why?"))
//                      listOne.append(Question(text: "What are things that you should not say at your own wedding?"))
//                      listOne.append(Question(text: "Is it harder to exercise more or eat healthier?"))
//                      listOne.append(Question(text: "Name things yous should not say during a job interview?"))
//                      listOne.append(Question(text: "What is the best things about living in your city?"))
//                      listOne.append(Question(text: "If you could live anywhere on earth, where would you live? And why?"))
//                      listOne.append(Question(text: "How would you define success?"))
//                      listOne.append(Question(text: "Name 3 vegetables."))
//                      listOne.append(Question(text: "Name famous tv shows?"))
//                      listOne.append(Question(text: "Name 3 news sources."))
//                      listOne.append(Question(text: "Name 3 illnesses."))
//                      listOne.append(Question(text: "What makes a business successful?"))
//                      listOne.append(Question(text: "Describe the smell of flowers."))
//                      listOne.append(Question(text: "In your opinion, what’s are the benefits of writing?"))
//                      listOne.append(Question(text: "Family guy or the Simpsons? And why?"))
//                      listOne.append(Question(text: "List things you will find at a train station."))
//                      listOne.append(Question(text: "List things you will find at the gym."))
//                      listOne.append(Question(text: "What's the longest amount of time you slept for?"))
//                      listOne.append(Question(text: "Name 3 vitamins."))
//                      listOne.append(Question(text: "What makes a shoe a good quality shoe?"))
//                      listOne.append(Question(text: "Name 4 super powers."))
//                      listOne.append(Question(text: "What is one thing you would change about your home?"))
//                      listOne.append(Question(text: "What are your thoughts on having a woman as a president of the USA?"))
//                      listOne.append(Question(text: "What was the last movie you saw?"))
//                      listOne.append(Question(text: "If you had a personal flag what would be on it?"))
//                      listOne.append(Question(text: "Name phobias people have."))
//                      listOne.append(Question(text: "What are  sources of  procrastination?"))
//                      listOne.append(Question(text: "List  foods you will never give up?"))
//                      listOne.append(Question(text: "Name places where you can buy a printer.?"))
//                      listOne.append(Question(text: "Name the benefits of drinking water"))
//                      listOne.append(Question(text: "Why are burgers considered unhealthy?"))
//                      listOne.append(Question(text: "Name places where you buy canned goods?"))
//                      listOne.append(Question(text: "When was the last time you stayed up all night? "))
//                      listOne.append(Question(text: "Would you rather go to the pool or the beach? And why?"))
//                      listOne.append(Question(text: "Describe today's day in one sentence"))
//                      listOne.append(Question(text: "What do people do too much of today?"))
//                      listOne.append(Question(text: "If you could be a character of a TV show who would it be? And why?"))
//                      listOne.append(Question(text: "What’s the best way to spend quarantine?"))
//                      listOne.append(Question(text: "What's the best way to spend a rainy afternoon?"))
//                      listOne.append(Question(text: "Would you leave your hometown forever or stay forever?"))
//                      listOne.append(Question(text: "List 3 electronic devices."))
//                      listOne.append(Question(text: "What's the most reliable source of news?"))
//                      listOne.append(Question(text: "Name reasons that can make someone late to work."))
//                      listOne.append(Question(text: "What will happen if we get rid of sugar?"))
//                      listOne.append(Question(text: "What will happen if we rid of gravity?"))
//                      listOne.append(Question(text: "What's your highest level of education?"))
//                      listOne.append(Question(text: "Describe your morning routine?"))
//                      listOne.append(Question(text: "Describe sleeping on a couch"))
//                      listOne.append(Question(text: "What's are the most populated city in the USA?"))
//                      listOne.append(Question(text: "What do you think lays beyond the galaxies?"))
//                      listOne.append(Question(text: "Which one is best: DC or Marvel? and why? "))
//                      listOne.append(Question(text: "Scary movies or adventure movies? And why? "))
//                      listOne.append(Question(text: "Have you ever forgotten someone's birthday?"))
//                      listOne.append(Question(text: "Is the glass half full or half empty? And why?"))
//                      listOne.append(Question(text: "What's the difference between millennials and generation Z?"))
//                      listOne.append(Question(text: "In your opinion, what are the benefits of taking naps?"))
//                      listOne.append(Question(text: "What is your opinion on fast food?"))
//                      listOne.append(Question(text: "What are the benefits of going to the gym?"))
//                      listOne.append(Question(text: "What self-isolation consist of ?"))
//                      listOne.append(Question(text: "What are the dangers of crossing on a red light?"))
//                      listOne.append(Question(text: "Try to describe being lost in the woods."))
//                      listOne.append(Question(text: "What are the dangers of driving a boat?"))
//                      listOne.append(Question(text: "What’s better quantity or quality? And why?"))
//                      listOne.append(Question(text: "Try to describe what it would be to live in space."))
//
//                      listOne.append(Question(text: "Describe the feeling of dropping your food on the floor"))
//                      listOne.append(Question(text: "Have you ever wished you were on TV? Explain your answer."))
//                      listOne.append(Question(text: " Try to describe what it would feel like to break bone. "))
//                      listOne.append(Question(text: "Name things you will find at a thanksgiving dinner table. "))
//                      listOne.append(Question(text: "Do you believe in religion? Explain your answer."))
//                      listOne.append(Question(text: "What family member inspire you the most?"))
//                      listOne.append(Question(text: "Name different ways of transportation "))
//                      listOne.append(Question(text: "Name the different brand of shoes you own."))
//                      listOne.append(Question(text: "Name different Ice cream flavors."))
//                      listOne.append(Question(text: "Name  famous disney movies?"))
//                      listOne.append(Question(text: "Who's are your favorite artists?"))
//                      listOne.append(Question(text: "Name things you will find at a laundromat."))
//                      listOne.append(Question(text: "Name ingredients to cook a burger."))
//                      listOne.append(Question(text: "Do you think global warming is real? if so, why?"))
//                      listOne.append(Question(text: "Name 5 languages."))
//                      listOne.append(Question(text: " What’s your opinion on electric cars."))
//                      listOne.append(Question(text: "Chicken soup or ramen noodle soup? And why?"))
//                      listOne.append(Question(text: "Pick one: Xbox, Playstation 4 or Nintendo Switch? Explain your answer."))
//                      listOne.append(Question(text: "What would happen if we use 100% of our brains? "))
//                      listOne.append(Question(text: "Is the nature of men good or evil? And why?"))
//                      listOne.append(Question(text: "Would you rather have something and lose it or never have it in the first place?"))
//                      listOne.append(Question(text: "What’s grammatically correct:  in a desert or on a desert?"))
//                      listOne.append(Question(text: "What came first: the chicken or the egg? Explain your answer."))
//                      listOne.append(Question(text: "What does the clothes you you have on right now says about you?"))
//                      listOne.append(Question(text: "Name 3 natural disasters."))
//                      listOne.append(Question(text: "List methods of communication."))
//                      listOne.append(Question(text: "What are two ways in which you can start an email?"))
//                      listOne.append(Question(text: "Would you rather be able to read people's thoughts or be invisible?"))
//                      listOne.append(Question(text: "Almond milk or regular milk? Explain your answer"))
//                      listOne.append(Question(text: "Netflix or hulu? Explain your answer"))
//                      listOne.append(Question(text: "Iced tea or hot tea? Explain your answer"))
//                      listOne.append(Question(text: "A walk through the park or a walk through the beach?"))
//                      listOne.append(Question(text: "Why do people clap when an airplane land safely?"))
//                      listOne.append(Question(text: "Why humans have a hard time letting go?"))
//                      listOne.append(Question(text: "Sunsets or sunrises? Explain your answer"))
//                      listOne.append(Question(text: "What are your thoughts on pineapple pizza?"))
//                      listOne.append(Question(text: "Are you afraid of heights? Explain your answer"))
//                      listOne.append(Question(text: "An asteroid will hit earth in 8 hours. How would you spend them?"))
//                      listOne.append(Question(text: "Mango or watermelon? Explain your answer"))
//                      listOne.append(Question(text: "Do you say conversate or converse? Explain your answer "))
//                      listOne.append(Question(text: "Liquid soap or soap bar? Explain your answer."))
//                      listOne.append(Question(text: "Clorox or Lysol? Explain your answer"))
//                      listOne.append(Question(text: "Strawberries or blueberries? and why?"))
//                      listOne.append(Question(text: "Starbucks or homemade coffee? and why?"))
//                      listOne.append(Question(text: "Are you a morning bird or a night owl? "))
//                      listOne.append(Question(text: "Tesla or BMW? Explain your answer"))
//                      listOne.append(Question(text: "Public transportation or driving? Explain your answer"))
//                      listOne.append(Question(text: "Cold weather or hot weather? Explain your answer"))
//                      listOne.append(Question(text: "Red wine or white wine? Explain your answer."))
//                      listOne.append(Question(text: "Chocolate chip cookie or outmeal cookie? and why?"))
//
//
//
              
              
              
              
              
              
        
        
    }
    
   
}
